version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      image: othaviohenrico:marvelcomicsecommerce:v1
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run serve    
